menu:
   æ–‡ç«  || iconfont icon-xiegenjin || faa-tada:
     å½’æ¡£: /archives/ || iconfont icon-shoujianxiang
     åˆ†ç±»: /categories/ || iconfont icon-shoujianxiangã€€|| faa-tada
     æ¸¸å®¢è®¿é—®: /census/ || iconfont icon-tongji || faa-tada
     å³åˆ»çŸ­æ–‡: /memos/ || iconfont icon-shejiao || faa-tada
   ç¤¾äº¤ || iconfont icon-shejiao || faa-tada:
     å‹é“¾: /links/ || iconfont icon-pengyou || faa-tada
     å‹åœˆ: /friends/ || iconfont icon-iconfontzhizuobiaozhunbduan36ã€€|| faa-tada
     è¯´è¯´: /artitalk/ || iconfont icon-shejiao || faa-tada
     å“”å“”ç‚¹å•¥: /bbtalk/ || iconfont icon-shejiao || faa-tada  
   å…³äº || iconfont icon-geren || faa-tada:
     çŸ­æ–‡: /ispeak/ || iconfont icon-xiegenjinã€€|| faa-tada
     å…³äº: /about/ || iconfont icon-geren || faa-tada
     éŸ³ä¹: /music/ || iconfont icon-yinle || faa-tada
   å°åŠŸèƒ½ || iconfont icon-gengduo || faa-tada:  
     æŠ¥çº¸: https://news.wyblog1.tk/ || iconfont icon-xinwen || faa-tada
     æœ¨é±¼: /muyu/ || iconfont icon-muyu1 || faa-tada
     
    

# The banner image of home page
index_img: https://source.fomal.cc/img/home_bg.webp

# Footer Background
footer_bg: false
background: url(https://source.fomal.cc/img/home_bg.webp)
inject:
  head:
     - <script src="https://cdn.staticfile.org/jquery/3.6.3/jquery.min.js"></script> # jQuery
     - <link rel="stylesheet" href="https://cdn1.tianli0.top/npm/element-ui@2.15.6/packages/theme-chalk/lib/index.css"> 
     - <script async data-pjax src="https://cdn.wpon.cn/2022-sucai/Gold-ingot.js"></script>  # æ–°å¹´å…ƒå®
     - <script async data-pjax src="/js/newYear.js"></script>  # æ–°å¹´å€’è®¡æ—¶
     - <script src="/js/nav.js"></script>
     - <script async src="/js/memos.js"></script>
     - <script src="/zhheo/random.js"></script>
     - <canvas id="universe"></canvas>
     - <script defer src="/js/universe.js"></script>
     - <script async data-pjax src="/js/txmap.js"></script> # è…¾è®¯ä½ç½®API
     - <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/l-lin/font-awesome-animation/dist/font-awesome-animation.min.css"  media="defer" onload="this.media='all'">
     - <link rel="stylesheet" href="//at.alicdn.com/t/c/font_3895868_mv3ae2gjui.css" media="defer" onload="this.media='all'">
     - <script async src="//at.alicdn.com/t/c/font_3895868_mv3ae2gjui.js"></script> 
     - <script src="/js/weibo.js"></script>
     - <script src="https://npm.elemecdn.com/echarts@4.9.0/dist/echarts.min.js"></script>
     - <link rel="stylesheet" href="/css/custom.css">
     - <link rel="stylesheet" href="/css/music.css">
     - <link rel="stylesheet" href="/css/footer.css">
     - <span id="fps"></span> # å¸§ç‡æ£€æµ‹
     - <script src="/js/notify.js"></script>
     - <script src="/js/moom.js"></script>
     - <script src="https://cdn.bootcdn.net/ajax/libs/clipboard.js/2.0.11/clipboard.min.js"></script>
     - <script src="/js/wyblog.js"></script>
     - <link rel="stylesheet" href="https://blog.leonus.cn/css/leonus.css?v1.11.23">
     - <script async src="https://raphamorim.io/waterfall.js/"></script> 
  bottom:  
     - <canvas id="universe"></canvas> # åˆ›å»ºç”»å¸ƒ
     - <script defer src="/js/cursor.js"></script>
     - <script defer="true" src="https://cdn.bootcdn.net/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
     - <script defer type="text/javascript" src="https://cdn1.tianli0.top/npm/sweetalert2@8.19.0/dist/sweetalert2.all.js"></script> # èŠ‚æ—¥å¼¹çª—ä¾èµ–
     - <script async src="/js/fps.js"></script> # å¸§ç‡æ£€
     - <script async data-pjax src="/js/flink_random.js"></script>
     - <script async data-pjax src="/js/card_author.js"></script>
     - <script src="/js/sun_moon.js" async></script>
     - <script defer src="https://cdn1.tianli0.top/gh/nextapps-de/winbox/dist/winbox.bundle.min.js"></script> # winboxæ”¯æŒ
     - <script type="text/javascript" src="/js/rightmenu.js"></script>
     - <script defer src="https://npm.elemecdn.com/jquery@latest/dist/jquery.min.js"></script>
     - <script defer="true" src="https://npm.elemecdn.com/jquery@latest/dist/jquery.min.js"></script>
     - <script defer="true" src="https://www.qcqx.cn/js/orlike.js"></script>
     - <script src="//cdn.bootcss.com/pace/1.0.2/pace.min.js">
     - <script charset="UTF-8" id="LA_COLLECT" src="https://sdk.51.la/js-sdk-pro.min.js"></script>
     - <script src="https://sdk.51.la/perf/js-sdk-perf.min.js" crossorigin="anonymous"></script>
     - <script> LA.init({id:"JyPwGVBiTFkmpfwz",ck:"JyPwGVBiTFkmpfwz"})</script>
     - <script>new LingQue.Monitor().init({id:"YOU ID",sendSuspicious:true});</script>
     - <script async src="https://cdn1.tianli0.top/npm/vue@2.6.14/dist/vue.min.js"></script> # å¼•å…¥VUE(f12)
     - <script async src="https://cdn1.tianli0.top/npm/element-ui@2.15.6/lib/index.js"></script> # å¼•å…¥ElementUI(f12)
wowjs:
  enable: true #æ§åˆ¶åŠ¨ç”»å¼€å…³ã€‚trueæ˜¯æ‰“å¼€ï¼Œfalseæ˜¯å…³é—­
  priority: 10 #è¿‡æ»¤å™¨ä¼˜å…ˆçº§
  mobile: false #ç§»åŠ¨ç«¯æ˜¯å¦å¯ç”¨ï¼Œé»˜è®¤ç§»åŠ¨ç«¯ç¦ç”¨
  animateitem:
    - class: recent-post-item #å¿…å¡«é¡¹ï¼Œéœ€è¦æ·»åŠ åŠ¨ç”»çš„å…ƒç´ çš„class
      style: animate__zoomIn #å¿…å¡«é¡¹ï¼Œéœ€è¦æ·»åŠ çš„åŠ¨ç”»
      duration: 2s #é€‰å¡«é¡¹ï¼ŒåŠ¨ç”»æŒç»­æ—¶é—´ï¼Œå•ä½å¯ä»¥æ˜¯msä¹Ÿå¯ä»¥æ˜¯sã€‚ä¾‹å¦‚3sï¼Œ700msã€‚
      delay: 1s #é€‰å¡«é¡¹ï¼ŒåŠ¨ç”»å¼€å§‹çš„å»¶è¿Ÿæ—¶é—´ï¼Œå•ä½å¯ä»¥æ˜¯msä¹Ÿå¯ä»¥æ˜¯sã€‚ä¾‹å¦‚3sï¼Œ700msã€‚
      offset: 100 #é€‰å¡«é¡¹ï¼Œå¼€å§‹åŠ¨ç”»çš„è·ç¦»ï¼ˆç›¸å¯¹æµè§ˆå™¨åº•éƒ¨ï¼‰
      iteration: 2 #é€‰å¡«é¡¹ï¼ŒåŠ¨ç”»é‡å¤çš„æ¬¡æ•°
    - class: card-widget
      style: animate__zoomIn
  animate_css: https://npm.elemecdn.com/hexo-butterfly-wowjs/lib/animate.min.css
  wow_js: https://npm.elemecdn.com/hexo-butterfly-wowjs/lib/wow.min.js
  wow_init_js: https://npm.elemecdn.com/hexo-butterfly-wowjs/lib/wow_init.js

# Comments System
# --------------------------------------

comments:
  # Up to two comments system, the first will be shown as default
  # Choose: Disqus/Disqusjs/Livere/Gitalk/Valine/Waline/Utterances/Facebook Comments/Twikoo/Giscus/Remark42/Artalk
  use: Twikoo,Artalk # Valine,Disqus
  text: true # Display the comment name next to the button
  # lazyload: The comment system will be load when comment element enters the browser's viewport.
  # If you set it to true, the comment count will be invalid
  lazyload: true
  count: false # Display comment count in post's top_img
  card_post_count: false # Display comment count in Home Page

# disqus
# https://disqus.com/
disqus:
  shortname:
  apikey: # For newest comments widget

# Alternative Disqus - Render comments with Disqus API
# DisqusJS è©•è«–ç³»çµ±ï¼Œå¯ä»¥å¯¦ç¾åœ¨ç¶²è·¯å¯©æŸ¥åœ°å€è¼‰å…¥ Disqus è©•è«–åˆ—è¡¨ï¼Œå…¼å®¹åŸç‰ˆ
# https://github.com/SukkaW/DisqusJS
disqusjs:
  shortname:
  apikey:
  option:

# livere (ä¾†å¿…åŠ›)
# https://www.livere.com/
livere:
  uid:

# gitalk
# https://github.com/gitalk/gitalk
gitalk:
  client_id:
  client_secret:
  repo:
  owner:
  admin:
  option:

# valine
# https://valine.js.org
valine:
  appId: # leancloud application app id
  appKey: # leancloud application app key
  avatar: monsterid # gravatar style https://valine.js.org/#/avatar
  serverURLs: # This configuration is suitable for domestic custom domain name users, overseas version will be automatically detected (no need to manually fill in)
  bg: # valine background
  visitor: false
  option:

# waline - A simple comment system with backend support fork from Valine
# https://waline.js.org/
waline:
  serverURL: https://waline.wyblog1.tk # Waline server address url
  bg: # waline background
  pageview: false
  option:

# utterances
# https://utteranc.es/
utterances:
  repo:
  # Issue Mapping: pathname/url/title/og:title
  issue_term: pathname
  # Theme: github-light/github-dark/github-dark-orange/icy-dark/dark-blue/photon-dark
  light_theme: github-light
  dark_theme: photon-dark

# Facebook Comments Plugin
# https://developers.facebook.com/docs/plugins/comments/
facebook_comments:
  app_id:
  user_id: # optional
  pageSize: 10 # The number of comments to show
  order_by: social # social/time/reverse_time
  lang: zh_TW # Language en_US/zh_CN/zh_TW and so on

# Twikoo
# https://github.com/imaegoo/twikoo
twikoo:
  envId: https://twikoo.wyblog1.tk
  region:
  visitor: true
  option:

# Giscus
# https://giscus.app/
giscus:
  repo:
  repo_id:
  category_id:
  theme:
    light: light
    dark: dark
  option:

# Remark42
# https://remark42.com/docs/configuration/frontend/
remark42:
  host: # Your Host URL
  siteId: # Your Site ID
  option:

# Artalk
# https://artalk.js.org/guide/frontend/config.html
artalk:
  server: https://wyblog-artalk.itisn.cyou/
  site: æ— å½±çš„artalk
  visitor: true
  el: #artalk-wrap
  locale: zh-CN
  pageSize: 20   // æ¯é¡µè¯„è®ºæ•°
  readMore: true // åŠ è½½æ›´å¤š or åˆ†é¡µæ¡
  autoLoad: true // è‡ªåŠ¨åŠ è½½ (åŠ è½½æ›´å¤š)
  option:
 
 
# Global font settings
# Don't modify the following settings unless you know how they work (éå¿…è¦ä¸è¦ä¿®æ”¹)
font:
  global-font-size: '15px'
  code-font-size: '14px'
  font-family: YSHST, -apple-system, 'Quicksand', 'Nimbus Roman No9 L', 'PingFang SC', 'Hiragino Sans GB', 'Noto Serif SC', 'Microsoft Yahei', 'WenQuanYi Micro Hei', 'ST Heiti', sans-serif;
  code-font-family: Consolas, YSHST, "Microsoft YaHei", Menlo, "PingFang SC", "Microsoft JhengHei", sans-serif

# å·¦ä¸Šè§’ç¶²ç«™åå­— ä¸»é å±…ä¸­ç¶²ç«™åå­—
blog_title_font:
  font_link: 
  font-family: YSHST, -apple-system, BlinkMacSystemFont, "Segoe UI" , "Helvetica Neue" , Lato, Roboto, "PingFang SC" , "Microsoft JhengHei" , "Microsoft YaHei" , sans-serif

# ä¸»é¡µå¡ç‰‡æ ·å¼
# Docs: https://akilar.top/posts/d6b69c49/
index_card_style: multicard # slidecard | multicard


# Display the article introduction on homepage
# 1: description
# 2: both (if the description exists, it will show description, or show the auto_excerpt)
# 3: auto_excerpt (default)
# false: do not show the article introduction
index_post_content:
  method: 2
  length: 500 # if you set method to 2 or 3, the length need to config

# electric_clock
# see https://anzhiy.cn/posts/fc18.html
electric_clock:
  enable: true # å¼€å…³
  priority: 5 #è¿‡æ»¤å™¨ä¼˜å…ˆæƒ
  enable_page: all # åº”ç”¨é¡µé¢
  exclude:
  # - /posts/
  # - /about/
  layout: # æŒ‚è½½å®¹å™¨ç±»å‹
    type: class
    name: sticky_layout
    index: 0
  loading: https://cdn.cbd.int/hexo-butterfly-clock-anzhiyu/lib/loading.gif #åŠ è½½åŠ¨ç”»è‡ªå®šä¹‰
  clock_css: https://cdn.cbd.int/hexo-butterfly-clock-anzhiyu/lib/clock.min.css
  clock_js: https://cdn.cbd.int/hexo-butterfly-clock-anzhiyu/lib/clock.min.js
  ip_api: https://widget.qweather.net/simple/static/js/he-simple-common.js?v=2.0
  qweather_key: # å’Œé£å¤©æ°”key
  gaud_map_key: # é«˜å¾—åœ°å›¾webæœåŠ¡key
  default_rectangle: false # å¼€å¯åå°†ä¸€ç›´æ˜¾ç¤ºrectangleä½ç½®çš„å¤©æ°”ï¼Œå¦åˆ™å°†è·å–è®¿é—®è€…çš„åœ°ç†ä½ç½®ä¸å¤©æ°”
  rectangle: 112.982279,28.19409 # è·å–è®¿é—®è€…ä½ç½®å¤±è´¥æ—¶ä¼šæ˜¾ç¤ºè¯¥ä½ç½®çš„å¤©æ°”ï¼ŒåŒæ—¶è¯¥ä½ç½®ä¸ºå¼€å¯default_rectangleåçš„ä½ç½®

# hexo-butterfly-categories-card
# see https://akilar.top/posts/a9131002/
categoryBar:
  enable: true # å¼€å…³
  priority: 5 #è¿‡æ»¤å™¨ä¼˜å…ˆæƒ
  enable_page: / # åº”ç”¨é¡µé¢
  layout: # æŒ‚è½½å®¹å™¨ç±»å‹
    type: id
    name: recent-posts
    index: 2
  column: odd # oddï¼š3åˆ— | evenï¼š4åˆ—
  row: 1 #æ˜¾ç¤ºè¡Œæ•°ï¼Œé»˜è®¤ä¸¤è¡Œï¼Œè¶…è¿‡è¡Œæ•°åˆ‡æ¢ä¸ºæ»šåŠ¨æ˜¾ç¤º
  message:
    - descr: bbtalkéƒ¨ç½²
      cover: https://images.boysec.cn/cover1.webp
    - descr: artitalkéƒ¨ç½²
      cover: https://images.boysec.cn/cover2.webp
    - descr: åšå®¢é­”æ”¹
      cover: https://www.wyblog1.tk/Cover/cover01.jpg  
  custom_css: https://npm.elemecdn.com/hexo-butterfly-categories-card@1.0.0/lib/categorybar.css

swiper:
    enable: true # å¼€å…³
    randomenable: true # åˆ›é€ åŠ›å¼€å…³
    priority: 5 #è¿‡æ»¤å™¨ä¼˜å…ˆæƒ
    enable_page: / # åº”ç”¨é¡µé¢
    timemode: date #date/updated
    layout: # æŒ‚è½½å®¹å™¨ç±»å‹
      type: id
      name: home_top
      index: 1
    category:
      - name: åšå®¢é­”æ”¹
        path: /categories/%E5%8D%9A%E5%AE%A2%E9%AD%94%E6%94%B9/
        shadow: var(--marcus-shadow-blue)
        class: blue
        icon: fas fa-dove
      - name: bbtalkéƒ¨ç½²
        path: /categories/bbtalk/
        shadow: var(--marcus-shadow-red)
        class: red
        icon: fas fa-burn
      - name: artitalkéƒ¨ç½²
        path: /categories/artitalk/
        shadow: var(--marcus-shadow-green)
        class: green
        icon: fas fa-book
    above_title: äººé—´å€¼å¾—
    below_title: æœªæ¥å¯æœŸ
    subtitle: BLOG.MARCUS233.TOP
    default_descr: å†æ€ä¹ˆçœ‹æˆ‘ä¹Ÿä¸çŸ¥é“æ€ä¹ˆæè¿°å®ƒçš„å•¦ï¼
    swiper_css: https://cdn1.tianli0.top/npm/hexo-butterfly-swiper-marcus@1.2.1/lib/swiper.min.css #swiper cssä¾èµ–
    swiper_js: https://cdn1.tianli0.top/npm/hexo-butterfly-swiper-marcus/lib/swiper.min.js #swiper jsä¾èµ– #swiper jsä¾èµ–
    custom_css: https://cdn1.tianli0.top/npm/hexo-butterfly-swiper-marcus@1.2.1/lib/swiperstyle.min.css # é€‚é…ä¸»é¢˜æ ·å¼è¡¥ä¸
    custom_js: https://cdn1.tianli0.top/npm/hexo-butterfly-swiper-marcus@1.2.1/lib/swiper_init.js # swiperåˆå§‹åŒ–æ–¹æ³•
    categorygroup_css: https://cdn1.tianli0.top/npm/hexo-butterfly-swiper-marcus@1.2.1/lib/categoryGroup.css
# Loading Animation (åŠ è½½åŠ¨ç”»)
preloader:
  enable: true
  # source
  # 1. fullpage-loading
  # 2. pace (progress bar)
  # else all
  source: 3
  # pace theme (see https://codebyzach.github.io/pace/)
  pace_css_url: /css/custom.css
  
popularPosts:
  eyeCatchImageAttributeName: headimg

related_post:
  enable: true
  limit: 6 # é¡¯ç¤ºæ¨è–¦æ–‡ç« æ•¸ç›®
  date_type: updated # or created or updated æ–‡ç« æ—¥æœŸé¡¯ç¤ºå‰µå»ºæ—¥æˆ–è€…æ›´æ–°æ—¥


# CDN
# Don't modify the following settings unless you know how they work
# éå¿…è¦è«‹ä¸è¦ä¿®æ”¹
CDN:
  # The CDN provider of internal scripts (ä¸»é¡Œå…§éƒ¨ js çš„ cdn é…ç½®)
  # option: local/jsdelivr/unpkg/cdnjs/custom
  # Dev version can only choose. ( devç‰ˆçš„ä¸»é¡Œåªèƒ½è¨­ç½®ç‚º local )
  internal_provider: local

  # The CDN provider of third party scripts (ç¬¬ä¸‰æ–¹ js çš„ cdn é…ç½®)
  # option: local/jsdelivr/unpkg/cdnjs/custom
  # when set it to local, you need to install hexo-butterfly-extjs
  third_party_provider: jsdelivr

  # Add version number to CDN, true or false  
  version: false

  # Custom format
  # For example: https://cdn.staticfile.org/${cdnjs_name}/${version}/${min_cdnjs_file}
  custom_format: https://cdn.staticfile.org/${cdnjs_name}/${version}/${min_cdnjs_file}

  option:
    coin_js: /js/coin.js
    coin_css: /css/coin.css
    # main_css:
    # main:
    # utils:
    # translate:
    # local_search:
    # algolia_js:
    # algolia_search_v4:
    # instantsearch_v4:
    # pjax:
    # gitalk:
    # gitalk_css:
    # blueimp_md5:
    # valine:
    # disqusjs:
    # disqusjs_css:
    # twikoo:
    # waline_js:
    # waline_css:
    # sharejs:
    # sharejs_css:
    # mathjax:
    # katex:
    # katex_copytex:
    # mermaid:
    # canvas_ribbon:
    # canvas_fluttering_ribbon:
    # canvas_nest:
    # lazyload:
    # instantpage:
    # typed:
    # pangu:
    # fancybox_css_v4:
    # fancybox_v4:
    # medium_zoom:
    # snackbar_css:
    # snackbar:
    # activate_power_mode:
    # fireworks:
    # click_heart:
    # ClickShowText:
    # fontawesomeV6:
    # flickr_justified_gallery_js:
    # flickr_justified_gallery_css:
    # aplayer_css:
    # aplayer_js:
    # meting_js:
    # prismjs_js:
    # prismjs_lineNumber_js:
    # prismjs_autoloader:
# copy settings
# copyright: Add the copyright information after copied content (å¤åˆ¶çš„å†…å®¹åé¢åŠ ä¸Šç‰ˆæƒä¿¡æ¯)
copy:
  enable: true
  copyright:
    enable: true
    limit_count: 50

# Post
# --------------------------------------

# toc (ç›®éŒ„)
toc:
  post: true
  page: false
  number: false
  expand: false
  style_simple: true # for post

post_copyright:
  enable: true
  decode: true
  author_href:
  license: CC BY-NC-SA 4.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/

# Sponsor/reward
reward:
  enable: true
  coinAudio: https://npm.elemecdn.com/akilar-candyassets@1.0.36/audio/aowu.m4a
  QR_code:
    - img: https://tuchuang.voooe.cn/images/2023/01/04/2.webp
      link:
      text: å¾®ä¿¡
    - img: https://tuchuang.voooe.cn/images/2023/01/04/20f8e49805975b8f8.webp
      link:
      text: æ”¯ä»˜å®

# figcaption (åœ–ç‰‡æè¿°æ–‡å­—)
photofigcaption: false

# post_pagination (åˆ†é )
# value: 1 || 2 || false
# 1: The 'next post' will link to old post
# 2: The 'next post' will link to new post
# false: disable pagination
post_pagination: 1

# Displays outdated notice for a post (æ–‡ç« éæœŸæé†’)
noticeOutdate:
  enable: true
  style: flat # style: simple/flat
  limit_day: 365 # When will it be shown
  position: top # position: top/bottom
  message_prev: It has been
  message_next: days since the last update, the content of the article may be outdated.

# å‹é“¾æ ·å¼ï¼Œbutterflyä¸ºé»˜è®¤æ ·å¼ï¼Œvolantisä¸ºç«™ç‚¹å¡ç‰‡æ ·å¼.flexcardä¸ºå¼¹æ€§å¡ç‰‡æ ·å¼
flink_style: volantis

# the subtitle on homepage (ä¸»é subtitle)
subtitle:
  enable: true
  # Typewriter Effect (æ‰“å­—æ•ˆæœ)
  effect: true
  # loop (å¾ªç’°æ‰“å­—)
  loop: true
  # source èª¿ç”¨ç¬¬ä¸‰æ–¹æœå‹™
  # source: false é—œé–‰èª¿ç”¨
  # source: 1  èª¿ç”¨ä¸€è¨€ç¶²çš„ä¸€å¥è©±ï¼ˆç°¡é«”ï¼‰ https://hitokoto.cn/
  # source: 2  èª¿ç”¨ä¸€å¥ç¶²ï¼ˆç°¡é«”ï¼‰ http://yijuzhan.com/
  # source: 3  èª¿ç”¨ä»Šæ—¥è©©è©ï¼ˆç°¡é«”ï¼‰ https://www.jinrishici.com/
  # subtitle æœƒå…ˆé¡¯ç¤º source , å†é¡¯ç¤º sub çš„å…§å®¹
  source: false
  # å¦‚æœé—œé–‰æ‰“å­—æ•ˆæœï¼Œsubtitle åªæœƒé¡¯ç¤º sub çš„ç¬¬ä¸€è¡Œæ–‡å­—
  sub:
    - "Welcome to æ— å½±ã®Tiny Home!ğŸ¤£ğŸ¤£ğŸ¤£"
    - "Hope you have a nice day!ğŸ­ğŸ­ğŸ­"
# æ ‡ç­¾å¤–æŒ‚
# tag-plugins-plus
# see https://akilar.top/posts/615e2dec/
tag_plugins:
  enable: true # å¼€å…³
  priority: 5 #è¿‡æ»¤å™¨ä¼˜å…ˆæƒ
  issues: true #issuesæ ‡ç­¾å¼€å…³
  link:
    placeholder: "/assets/coffee.png" #link_cardæ ‡ç­¾é»˜è®¤çš„å›¾æ ‡å›¾ç‰‡
  CDN:
    anima: https://npm.elemecdn.com/hexo-butterfly-tag-plugins-plus@latest/lib/assets/font-awesome-animation.min.css #åŠ¨ç”»æ ‡ç­¾animaçš„ä¾èµ–
    jquery: https://cdn.staticfile.org/jquery/3.6.3/jquery.min.js #issuesæ ‡ç­¾ä¾èµ–
    issues: https://npm.elemecdn.com/hexo-butterfly-tag-plugins-plus@latest/lib/assets/issues.js #issuesæ ‡ç­¾ä¾èµ–
    carousel: https://npm.elemecdn.com/hexo-butterfly-tag-plugins-plus@latest/lib/assets/carousel-touch.js
    tag_plugins_css: https://npm.elemecdn.com/hexo-butterfly-tag-plugins-plus@latest/lib/tag_plugins.css

# Theme color for customize
# Notice: color value must in double quotes like "#000" or may cause error!

theme_color:
  enable: true
  main: # "#49b1f5"
  paginator: # "#49b1f5"
  button_hover: # "#FF7242"
  text_selection: # "#49b1f5" # "#00c4b6"
  link_color: "#a591e0"
  meta_color: "#858585"
  hr_color: "#A4D8FA"
  code_foreground: # "#F47466"
  code_background: # "rgba(27, 31, 35, .05)"
  toc_color: # "#49b1f5" # "#00c4b6"
  blockquote_padding_color: # "#49b1f5"
  blockquote_background_color: # "#49b1f5"
  scrollbar_color: # "#49b1f5"
  meta_theme_color_light: "ffffff"
  meta_theme_color_dark: "#0d0d0d"

darkmode:
  enable: true
  # Toggle Button to switch dark/light mode
  button: false
  # Switch dark/light mode automatically (è‡ªå‹•åˆ‡æ› dark modeå’Œ light mode)
  # autoChangeMode: 1  Following System Settings, if the system doesn't support dark mode, it will switch dark mode between 6 pm to 6 am
  # autoChangeMode: 2  Switch dark mode between 6 pm to 6 am
  # autoChangeMode: false
  autoChangeMode: 2
  # Set the switch time. The value is between 0 and 12. If not set, the default value is 6
  am: 6
  pm: 6
