menu:
   主页: / || fa-solid fa-house-chimney
   文章 || fa-solid fa-book-reader:
    归档: /archives/ || fa-solid fa-box-archive
    分类: /categories/ || fa-solid fa-folder-open
   社交 || fa-solid fa-cubes:
    友链: /links/ || fa-solid fa-link
    友圈: /friends/ || fa-solid fa-blog
    短文: /ispeak/ || fa-solid fa-comment-alt
   说说 || fa-solid fa-desktop:
    artitalk: /artitalk/ || fa-solid fa-link
    bbtalk: /bbtalk/ || fa-solid fa-blog

# hexo-butterfly-swiper
# see https://akilar.top/posts/8e1264d1/
swiper:
  enable: true # 开关
  priority: 5 #过滤器优先权
  enable_page: all # 应用页面
  timemode: date #date/updated
  layout: # 挂载容器类型
    type: id
    name: recent-posts
    index: 0
  default_descr: 再怎么看我也不知道怎么描述它的啦！
  swiper_css: https://npm.elemecdn.com/hexo-butterfly-swiper/lib/swiper.min.css #swiper css依赖
  swiper_js: https://npm.elemecdn.com/hexo-butterfly-swiper/lib/swiper.min.js #swiper js依赖
  custom_css: https://npm.elemecdn.com/hexo-butterfly-swiper/lib/swiperstyle.css # 适配主题样式补丁
  custom_js: https://npm.elemecdn.com/hexo-butterfly-swiper/lib/swiper_init.js # swiper初始化方法

inject:
  head:
     - <link rel="stylesheet" href="/css/cat.css">
     - <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/wyblog11/661111@main/source/css/custom.css">
  bottom:   
     - <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/wyblog11/661111@main/source/css/custom/custom.css">
     - <script defer src="https://npm.elemecdn.com/jquery@latest/dist/jquery.min.js"></script>
     - <script defer data-pjax src="/js/cat.js"></script>

# hexo-butterfly-categories-card
# see https://akilar.top/posts/a9131002/
categoryBar:
  enable: true # 开关
  priority: 5 #过滤器优先权
  enable_page: / # 应用页面
  layout: # 挂载容器类型
    type: id
    name: recent-posts
    index: 0
  column: odd # odd：3列 | even：4列
  row: 1 #显示行数，默认两行，超过行数切换为滚动显示
  message:
    - descr: bbtalk部署
      cover: https://images.boysec.cn/cover1.webp
    - descr: artitalk部署
      cover: https://images.boysec.cn/cover2.webp
  custom_css: https://npm.elemecdn.com/hexo-butterfly-categories-card@1.0.0/lib/categorybar.css
