menu:
   主页: / || fa-solid fa-house-chimney
   文章 || fa-solid fa-book-reader:
    归档: /archives/ || fa-solid fa-box-archive
    分类: /categories/ || fa-solid fa-folder-open
   社交 || fa-solid fa-cubes:
    友链: /links/ || fa-solid fa-link
    友圈: /friends/ || fa-solid fa-blog
    短文: /ispeak/ || fa-solid fa-comment-alt
   说说 || fa-solid fa-desktop:
    artitalk: /artitalk/ || fa-solid fa-link
    bbtalk: /bbtalk/ || fa-solid fa-blog

# hexo-butterfly-swiper
# see https://akilar.top/posts/8e1264d1/
swiper:
  enable: true # 开关
  priority: 5 #过滤器优先权
  enable_page: all # 应用页面
  timemode: date #date/updated
  layout: # 挂载容器类型
    type: id
    name: recent-posts
    index: 2
  default_descr: 再怎么看我也不知道怎么描述它的啦！
  swiper_css: https://npm.elemecdn.com/hexo-butterfly-swiper/lib/swiper.min.css #swiper css依赖
  swiper_js: https://npm.elemecdn.com/hexo-butterfly-swiper/lib/swiper.min.js #swiper js依赖
  custom_css: https://npm.elemecdn.com/hexo-butterfly-swiper/lib/swiperstyle.css # 适配主题样式补丁
  custom_js: https://npm.elemecdn.com/hexo-butterfly-swiper/lib/swiper_init.js # swiper初始化方法

inject:
  head:
     - <link rel="stylesheet" href="/css/nav.css">
     - <link rel="stylesheet" href="/css/side.css">
     - <link rel="stylesheet" href="/css/cat.css">
     - <link rel="stylesheet" href="/css/head.css" media="defer" onload="this.media='all'">
     - <link rel="stylesheet" href="/css/custom.css">
     - <link rel="stylesheet" href="/css/universe.css">
     - <style id="themeColor"></style> # 主题色
     - <style id="rightSide"></style> # 侧边栏
     - <style id="transPercent"></style> # 透明度调节
     - <style id="blurNum"></style> # 模糊半径调节
     - <style id="settingStyle"></style> # 模糊效果开关
     - <span id="fps"></span> # 帧率检测
     - <style id="defineBg"></style> # 自定义背景选项
  bottom:   
     - <link rel="stylesheet" href="/css/custom/custom.css">
     - <script defer src="https://npm.elemecdn.com/jquery@latest/dist/jquery.min.js"></script>
     - <script defer data-pjax src="/js/cat.js"></script>
     - <canvas id="universe"></canvas>
     - <script defer src="/js/universe.js"></script>
     - <script src="/js/sun_moon.js" async></script>
     - <script defer src="https://cdn1.tianli0.top/gh/nextapps-de/winbox/dist/winbox.bundle.min.js"></script> # winbox支持
     - <script defer data-pjax src="/static/js/meihua.js"></script> # 美化模块  

# hexo-butterfly-categories-card
# see https://akilar.top/posts/a9131002/
categoryBar:
  enable: true # 开关
  priority: 5 #过滤器优先权
  enable_page: / # 应用页面
  layout: # 挂载容器类型
    type: id
    name: recent-posts
    index: 3
  column: odd # odd：3列 | even：4列
  row: 1 #显示行数，默认两行，超过行数切换为滚动显示
  message:
    - descr: bbtalk部署
      cover: https://images.boysec.cn/cover1.webp
    - descr: artitalk部署
      cover: https://images.boysec.cn/cover2.webp
  custom_css: https://npm.elemecdn.com/hexo-butterfly-categories-card@1.0.0/lib/categorybar.css

# The banner image of home page
index_img: false
# Footer Background
footer_bg: false

background: url(https://source.fomal.cc/img/home_bg.webp)

# hexo-filter-gitcalendar
gitcalendar:
  enable: true # 开关
  priority: 5 #过滤器优先权
  enable_page: / # 应用页面
  # butterfly挂载容器
  layout: # 挂载容器类型
    type: id
    name: recent-posts
    index: 4
  user: 612901 #git用户名
  apiurl: 'https://gitcalendar.fomal.cc'	# 这是我的API，最好自己弄一个
  minheight:
    pc: 280px #桌面端最小高度
    mibile: 0px #移动端最小高度
  # color: "['#d9e0df', '#c6e0dc', '#a8dcd4', '#9adcd2', '#89ded1', '#77e0d0', '#5fdecb', '#47dcc6', '#39dcc3', '#1fdabe', '#00dab9']" # 目前我在用的
  # "['#e4dfd7', '#f9f4dc', '#f7e8aa', '#f7e8aa', '#f8df72', '#fcd217', '#fcc515', '#f28e16', '#fb8b05', '#d85916', '#f43e06']" #橘黄色调
  color: "['#ebedf0', '#fdcdec', '#fc9bd9', '#fa6ac5', '#f838b2', '#f5089f', '#c4067e', '#92055e', '#540336', '#48022f', '#30021f']" #浅紫色调
  # color: "['#ebedf0', '#f0fff4', '#dcffe4', '#bef5cb', '#85e89d', '#34d058', '#28a745', '#22863a', '#176f2c', '#165c26', '#144620']" #翠绿色调
  # color: "['#ebedf0', '#f1f8ff', '#dbedff', '#c8e1ff', '#79b8ff', '#2188ff', '#0366d6', '#005cc5', '#044289', '#032f62', '#05264c']" #天青色调
  container: .recent-post-item(style='width:100%;height:auto;padding:10px;') #父元素容器，需要使用pug语法
  gitcalendar_css: https://npm.elemecdn.com/hexo-filter-gitcalendar/lib/gitcalendar.css
  gitcalendar_js: https://npm.elemecdn.com/hexo-filter-gitcalendar/lib/gitcalendar.js	
preloader:
  enable: true
  # source
  # 1. fullpage-loading
  # 2. pace (progress bar)
  source: 3
  # pace theme (see https://codebyzach.github.io/pace/)
  pace_css_url: https://fastly.jsdelivr.net/gh/xlenco/JS-X@main/pace.js/pace.css

# 背景由js指定
background:
  default: var(--default-bg)
  darkmode: var(--darkmode-bg)
  mobileday: var(--mobileday-bg)
  mobilenight: var(--mobilenight-bg)
  
# 字体由js指定  
font:
  global-font-size: "15px"
  code-font-size: "14px"
  font-family: var(--global-font), -apple-system, 'Quicksand', 'Nimbus Roman No9 L', 'PingFang SC', 'Hiragino Sans GB', 'Noto Serif SC', 'Microsoft Yahei', 'WenQuanYi Micro Hei', 'ST Heiti', sans-serif;
  code-font-family: Consolas_1, var(--global-font), "Microsoft YaHei", Menlo, "PingFang SC", "Microsoft JhengHei", sans-serif

blog_title_font:
  font_link:
  font-family: var(--global-font)

# 主题色由js指定，因此部分需要留空，避免冗余加载  
theme_color:
  enable: true
  main: 
  paginator: 
  button_hover: 
  text_selection: 
  link_color: "#a591e0"
  meta_color: "#858585"
  hr_color: "#A4D8FA"
  code_foreground: 
  code_background: 
  toc_color: 
  blockquote_padding_color: 
  blockquote_background_color: 
  scrollbar_color: 
  meta_theme_color_light: "ffffff"
  meta_theme_color_dark: "#0d0d0d"  
